### PR TITLE
Add MoSCoW method for requirements.

### PR DESCRIPTION
**Pull request by LourensVeen**
MoSCoW is a simple method which gives a bit of structure to the list of requirements. We should use it.

### CODE REVIEW

**Comment by mkuzak** [comment]
I think that should be part of roadmap. Currently we're missing ROADMAP.md we should think about it and I this would go into this file in my opinion.

**Comment by blootsvoets** [comment]
I think what Lourens means is to use this MoSCoW method on the estep-checklist. In my opinion, if we use Github milestones correctly (I don't think any NLeSC project does), there isn't that much need for ROADMAP.md. Of course, in milestones we could also use the MoSCoW method.

**Comment by mkuzak** [comment]
I think Lourens meant MoScoW for the software. At least that's what I can tell from the file changes in pull request. @LourensVeen please correct :).
I do think roadmap becomes important when you want to attract external contributors. People will want to know that the project is going the same direction they are interested in if they're going to invest their time in it.

**Comment by LourensVeen** [comment]
No, I meant using MoSCoW for the software, not for the checklist. Although of course we could apply the checklist to the checklist and ascend to a meta-recursive state of zen, but then we need to order Mateusz some wireless headphones so he can float through the office unrestrained by cabling.

Anyway, my main point is that MoSCoW is a nice tool for organising requirements, and that we should use it, mainly at the beginning of a project and at any re-plannings along the way.

The list of MoSCoW-prioritised requirements could be on the project manager's laptop, but why not make it part of the project documentation? As Mateusz says, it's nice for (potential) external contributors to have an idea of where we are going.

**Comment by jiskattema** [comment]
You can easily do it in github with Labels; just standardize on the naming. 'Must' = blocker, 'Should' = highly desired / milestone, 'Could' = potential feature, 'Would' = nice to have, but dont wait for it.

Or, an alternative interpretation:
Must: certain
Should: likely
Could: not likely
Wont: definitely not

**Comment by LourensVeen** [comment]
Well, but then you'd need some rather broad issues, which would be open for the duration of most of the project. Maybe it's better to have that separate from the day-to-day work?

**Comment by mkuzak** [comment]
Migrated to https://github.com/NLeSC/guide/issues/17

**Pull request closed without merging**
